blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/username/wifi-manager/discussions
    about: Please ask and answer questions here
  - name: Documentation
    url: https://github.com/username/wifi-manager/wiki
    about: Check our documentation for help 